CREATE DATABASE IF NOT EXISTS nasdaq;
GRANT ALL PRIVILEGES on nasdaq.* TO 'nasdaq'@'%' IDENTIFIED BY 'nasdaq' WITH GRANT OPTION;
CREATE DATABASE IF NOT EXISTS nasdaq_test;
GRANT ALL PRIVILEGES on nasdaq_test.* TO 'nasdaq_test'@'%' IDENTIFIED BY 'nasdaq_test' WITH GRANT OPTION;